# Notebook 1: QSARmil multi-conformer modelling

This notebook introduces the high-level API for building multi-conformer models with **QSARmil**. The API is designed to simplify benchmarking QSARmil against alternative approaches without requiring detailed knowledge of the underlying modelling configuration. As a result, the workflow remains concise and easy to follow. You can adapt the code below to your own dataset and run the complete **QSARmil** modelling pipeline with minimal modifications.

In [1]:
import pandas as pd

from sklearn.metrics import r2_score

### 1. Data load

As an example, we use a publicly available and easily accessible collection of molecular bioactivity datasets introduced in the paper by:

> Van Tilborg, Derek, Alisa Alenicheva, and Francesca Grisoni. "Exposing the limitations of molecular machine learning with activity cliffs." Journal of chemical information and modeling 62.23 (2022): 5938-5951.

From this collection, we select one dataset for demonstration purposes.

In [ ]:
# load data
url = "https://raw.githubusercontent.com/molML/MoleculeACE/main/MoleculeACE/Data/benchmark_data/CHEMBL2034_Ki.csv"
df_ace = pd.read_csv(url)

# train/test split
df_train = df_ace[df_ace["split"] == "train"][["smiles", "y"]]
df_test = df_ace[df_ace["split"] == "test"][["smiles", "y"]]

In [3]:
# uncomment for quick testing
# df_train = df_train.sample(frac=0.1, random_state=42).reset_index(drop=True)
# df_test = df_test.sample(frac=0.1, random_state=42).reset_index(drop=True)
# df_train.shape, df_test.shape

((60, 2), (15, 2))

### 2. Data validation

The data validation step is straightforward but includes an additional requirement compared to standard 2D modelling pipelines. In most QSAR workflows, input structures are primarily validated by checking whether their SMILES strings are valid and can be successfully parsed into molecular objects.

In contrast, **QSARmil** introduces an extra validation step: verifying whether a valid 3D structure can be generated for each molecule. Molecules that fail this step cannot be used in the 3D modelling pipeline. As a result, the filtering (removal) rate in QSARmil may be higher than in typical 2D QSAR workflows.

In [4]:
from qsarmil.data.input_data import DataValidator

In [5]:
dvalid = DataValidator(num_cpu=30, verbose=True)

df_train = dvalid.filter_dataframe(df_train)
df_test = dvalid.filter_dataframe(df_test)

No rows removed. All molecules are valid.
No rows removed. All molecules are valid.

### 3. Building model

The multi-conformer model building pipeline consists of several sequential steps:

 - Conformer generation: the maximum number of conformers is defined using the ``num_conf`` parameter.
 - Descriptor calculation: by default, multiple types of 3D molecular descriptors are computed.
 - Model training: several multi-instance learning networks are used to train models. Internal stepwise hyperparameter optimization can be enabled with ``hopt=True`` (note that this increases runtime).
 - Consensus search: once multiple multi-conformer models are trained, a genetic algorithm is applied to identify an optimal consensus model.

Task type is defined automatically (regression or binary classification), ``output_folder`` (directory for storing predictions from individual models), and ``verbose`` (controls the level of pipeline progress output).

In [6]:
from qsarmil.meta import MultiConformerModel

In [7]:
model = MultiConformerModel(num_conf=10, hopt=False, output_folder="mcf", verbose=True)
df_pred = model.run_predict(df_train, df_test)

No rows removed. All molecules are valid.
No rows removed. All molecules are valid.
No rows removed. All molecules are valid.
Generating conformers: 48/48
Generating conformers: 12/12
Generating conformers: 12/12
[1/108] Running model: RDKitGEOM|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.03 min | Memory usage: 1.156 GB
[2/108] Running model: RDKitGEOM|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.157 GB
[3/108] Running model: RDKitGEOM|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.163 GB
[4/108] Running model: RDKitGEOM|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.150 GB
[5/108] Running model: RDKitGEOM|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.149 GB
[6/108] Running model: RDKitGEOM|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.150 GB
[7/108] Running model: RDKitGEOM|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.151 GB
[8/108] Running model: RDKitGEOM|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.153 GB
[9/108] Running model: RDKitGEOM|Ridge
  > Finished in 0.00 min | Memory usage: 1.157 GB
[10/108] Running model: RDKitGEOM|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.157 GB
[11/108] Running model: RDKitGEOM|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.157 GB
[12/108] Running model: RDKitGEOM|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.169 GB
[13/108] Running model: RDKitAUTOCORR|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.11 min | Memory usage: 1.233 GB
[14/108] Running model: RDKitAUTOCORR|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.235 GB
[15/108] Running model: RDKitAUTOCORR|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.243 GB
[16/108] Running model: RDKitAUTOCORR|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.238 GB
[17/108] Running model: RDKitAUTOCORR|AdditiveAttentionNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.239 GB
[18/108] Running model: RDKitAUTOCORR|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.240 GB
[19/108] Running model: RDKitAUTOCORR|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.240 GB
[20/108] Running model: RDKitAUTOCORR|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.241 GB
[21/108] Running model: RDKitAUTOCORR|Ridge
  > Finished in 0.00 min | Memory usage: 1.241 GB
[22/108] Running model: RDKitAUTOCORR|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.241 GB
[23/108] Running model: RDKitAUTOCORR|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.241 GB
[24/108] Running model: RDKitAUTOCORR|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.241 GB
[25/108] Running model: RDKitRDF|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.06 min | Memory usage: 1.243 GB
[26/108] Running model: RDKitRDF|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.245 GB
[27/108] Running model: RDKitRDF|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.252 GB
[28/108] Running model: RDKitRDF|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.250 GB
[29/108] Running model: RDKitRDF|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.252 GB
[30/108] Running model: RDKitRDF|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.256 GB
[31/108] Running model: RDKitRDF|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.257 GB
[32/108] Running model: RDKitRDF|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.260 GB
[33/108] Running model: RDKitRDF|Ridge
  > Finished in 0.00 min | Memory usage: 1.260 GB
[34/108] Running model: RDKitRDF|MLPRegressor
  > Finished in 0.03 min | Memory usage: 1.261 GB
[35/108] Running model: RDKitRDF|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.261 GB
[36/108] Running model: RDKitRDF|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.266 GB
[37/108] Running model: RDKitMORSE|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.13 min | Memory usage: 1.270 GB
[38/108] Running model: RDKitMORSE|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.270 GB
[39/108] Running model: RDKitMORSE|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.277 GB
[40/108] Running model: RDKitMORSE|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.278 GB
[41/108] Running model: RDKitMORSE|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.280 GB
[42/108] Running model: RDKitMORSE|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.283 GB
[43/108] Running model: RDKitMORSE|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.285 GB
[44/108] Running model: RDKitMORSE|DynamicPoolingNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.287 GB
[45/108] Running model: RDKitMORSE|Ridge
  > Finished in 0.00 min | Memory usage: 1.287 GB
[46/108] Running model: RDKitMORSE|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.287 GB
[47/108] Running model: RDKitMORSE|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.287 GB
[48/108] Running model: RDKitMORSE|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.293 GB
[49/108] Running model: RDKitWHIM|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.08 min | Memory usage: 1.294 GB
[50/108] Running model: RDKitWHIM|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.295 GB
[51/108] Running model: RDKitWHIM|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.299 GB
[52/108] Running model: RDKitWHIM|MeanInstanceNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.293 GB
[53/108] Running model: RDKitWHIM|AdditiveAttentionNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.293 GB
[54/108] Running model: RDKitWHIM|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.294 GB
[55/108] Running model: RDKitWHIM|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.294 GB
[56/108] Running model: RDKitWHIM|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.294 GB
[57/108] Running model: RDKitWHIM|Ridge
  > Finished in 0.00 min | Memory usage: 1.294 GB
[58/108] Running model: RDKitWHIM|MLPRegressor
  > Finished in 0.03 min | Memory usage: 1.294 GB
[59/108] Running model: RDKitWHIM|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.294 GB
[60/108] Running model: RDKitWHIM|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.294 GB
[61/108] Running model: MolFeatUSRD|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.08 min | Memory usage: 1.311 GB
[62/108] Running model: MolFeatUSRD|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.311 GB
[63/108] Running model: MolFeatUSRD|MeanBagNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.313 GB
[64/108] Running model: MolFeatUSRD|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.313 GB
[65/108] Running model: MolFeatUSRD|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.322 GB
[66/108] Running model: MolFeatUSRD|SelfAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.324 GB
[67/108] Running model: MolFeatUSRD|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.324 GB
[68/108] Running model: MolFeatUSRD|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.326 GB
[69/108] Running model: MolFeatUSRD|Ridge
  > Finished in 0.00 min | Memory usage: 1.326 GB
[70/108] Running model: MolFeatUSRD|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.326 GB
[71/108] Running model: MolFeatUSRD|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.326 GB
[72/108] Running model: MolFeatUSRD|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.326 GB
[73/108] Running model: MolFeatElectroShape|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.13 min | Memory usage: 1.340 GB
[74/108] Running model: MolFeatElectroShape|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.341 GB
[75/108] Running model: MolFeatElectroShape|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.346 GB
[76/108] Running model: MolFeatElectroShape|MeanInstanceNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.344 GB
[77/108] Running model: MolFeatElectroShape|AdditiveAttentionNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.347 GB
[78/108] Running model: MolFeatElectroShape|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.349 GB
[79/108] Running model: MolFeatElectroShape|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.349 GB
[80/108] Running model: MolFeatElectroShape|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.349 GB
[81/108] Running model: MolFeatElectroShape|Ridge
  > Finished in 0.00 min | Memory usage: 1.349 GB
[82/108] Running model: MolFeatElectroShape|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.349 GB
[83/108] Running model: MolFeatElectroShape|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.349 GB
[84/108] Running model: MolFeatElectroShape|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.349 GB
[85/108] Running model: RDKitGETAWAY|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.11 min | Memory usage: 1.379 GB
[86/108] Running model: RDKitGETAWAY|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.380 GB
[87/108] Running model: RDKitGETAWAY|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.391 GB
[88/108] Running model: RDKitGETAWAY|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.388 GB
[89/108] Running model: RDKitGETAWAY|AdditiveAttentionNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.392 GB
[90/108] Running model: RDKitGETAWAY|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.394 GB
[91/108] Running model: RDKitGETAWAY|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.395 GB
[92/108] Running model: RDKitGETAWAY|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.399 GB
[93/108] Running model: RDKitGETAWAY|Ridge
  > Finished in 0.00 min | Memory usage: 1.399 GB
[94/108] Running model: RDKitGETAWAY|MLPRegressor
  > Finished in 0.00 min | Memory usage: 1.399 GB
[95/108] Running model: RDKitGETAWAY|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.399 GB
[96/108] Running model: RDKitGETAWAY|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.397 GB
[97/108] Running model: MolFeatPmapper|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.04 min | Memory usage: 1.453 GB
[98/108] Running model: MolFeatPmapper|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.460 GB
[99/108] Running model: MolFeatPmapper|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.481 GB
[100/108] Running model: MolFeatPmapper|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.497 GB
[101/108] Running model: MolFeatPmapper|AdditiveAttentionNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.507 GB
[102/108] Running model: MolFeatPmapper|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.517 GB
[103/108] Running model: MolFeatPmapper|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.531 GB
[104/108] Running model: MolFeatPmapper|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.546 GB
[105/108] Running model: MolFeatPmapper|Ridge
  > Finished in 0.00 min | Memory usage: 1.546 GB
[106/108] Running model: MolFeatPmapper|MLPRegressor
  > Finished in 0.02 min | Memory usage: 1.549 GB
[107/108] Running model: MolFeatPmapper|LinearSVR
  > Finished in 0.00 min | Memory usage: 1.552 GB
[108/108] Running model: MolFeatPmapper|XGBRegressor
  > Finished in 0.00 min | Memory usage: 1.557 GB

Running genetic consensus search ...
Note: this step's randomness isn't controlled by `seed` - qsarcons.GeneticSearch doesn't expose one.
Best consensus:
RDKitGETAWAY|HopfieldAttentionNetworkRegressor
RDKitMORSE|DynamicPoolingNetworkRegressor
No rows removed. All molecules are valid.
Generating conformers: 15/15

In [8]:
r2_score(df_test["y"], df_pred["pred"])

-0.14114062286340046

In [9]:
model.save("./mcf_model.pkl")

In [10]:
preds = model.predict(df_test)
preds

No rows removed. All molecules are valid.
Generating conformers: 15/15

                                               SMILES      pred
0   C[C@H]1c2c(cc(F)c(-c3cccc4c(Cl)c[nH]c34)c2F)NC... -0.476415
1   CNC(=O)C[C@H]1COc2cc(F)c(CC(C)C)cc2N1C(=O)c1cc... -2.145822
2   CNC(=O)c1cccc(CC[C@]2(O)CCC3=Cc4c(cnn4-c4ccc(F... -0.755361
3   CC(=O)[C@@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@... -3.595975
4   Cn1cc(S(=O)(=O)N2CC[C@H]3Cc4c(cnn4-c4ccc(F)cc4... -0.918810
5   C[C@]12C[C@H](O)[C@@]3(F)[C@@H](C[C@H](F)C4=CC... -0.163074
6   COc1c(O)ccc2c1-c1ccc3c(c1/C(=C/c1sccc1C(O)C(F)...  0.162156
7      C=C1C[C@H](C)CC(C)(C)[C@@H]1Cc1cc(OC)c(Br)cc1O -3.912309
8   CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccc(F)c(F)c1)... -0.897310
9      CC1=CC(C)(C)Nc2ccc3c(c21)C(CCC(C)C)Oc1ccccc1-3 -2.240120
10  O=C(c1ccccn1)[C@]12Cc3cnn(-c4ccc(F)cc4)c3C[C@@... -1.538250
11  Cc1ccnc(C(=O)[C@]23Cc4cnn(-c5ccc(F)cc5)c4C=C2C... -0.017588
12  CC(C)(C(=O)Nc1nccs1)C(c1ccc2c(cnn2-c2ccc(F)cc2... -0.458741
13    CC1=CC(C)(C)Nc2ccc3c(c21)C(c1ccccc1)Oc1ccccc1-3 -1.721700
14  C[C@H]1c2c(cc(F)c(-c3cccc4cc[nH]c34)c2F)NC(C)(... -1.097445

In [11]:
r2_score(df_test["y"], preds["pred"])

-0.14114062286340046

In [12]:
MultiConformerModel.predictFromSMILES("./mcf_model.pkl", df_test["smiles"])

No rows removed. All molecules are valid.
Generating conformers: 15/15

                                               SMILES      pred
0   C[C@H]1c2c(cc(F)c(-c3cccc4c(Cl)c[nH]c34)c2F)NC... -0.476415
1   CNC(=O)C[C@H]1COc2cc(F)c(CC(C)C)cc2N1C(=O)c1cc... -2.145822
2   CNC(=O)c1cccc(CC[C@]2(O)CCC3=Cc4c(cnn4-c4ccc(F... -0.755361
3   CC(=O)[C@@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@... -3.595975
4   Cn1cc(S(=O)(=O)N2CC[C@H]3Cc4c(cnn4-c4ccc(F)cc4... -0.918810
5   C[C@]12C[C@H](O)[C@@]3(F)[C@@H](C[C@H](F)C4=CC... -0.163074
6   COc1c(O)ccc2c1-c1ccc3c(c1/C(=C/c1sccc1C(O)C(F)...  0.162156
7      C=C1C[C@H](C)CC(C)(C)[C@@H]1Cc1cc(OC)c(Br)cc1O -3.912309
8   CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccc(F)c(F)c1)... -0.897310
9      CC1=CC(C)(C)Nc2ccc3c(c21)C(CCC(C)C)Oc1ccccc1-3 -2.240120
10  O=C(c1ccccn1)[C@]12Cc3cnn(-c4ccc(F)cc4)c3C[C@@... -1.538250
11  Cc1ccnc(C(=O)[C@]23Cc4cnn(-c5ccc(F)cc5)c4C=C2C... -0.017588
12  CC(C)(C(=O)Nc1nccs1)C(c1ccc2c(cnn2-c2ccc(F)cc2... -0.458741
13    CC1=CC(C)(C)Nc2ccc3c(c21)C(c1ccccc1)Oc1ccccc1-3 -1.721700
14  C[C@H]1c2c(cc(F)c(-c3cccc4cc[nH]c34)c2F)NC(C)(... -1.097445