# Notebook 1: QSARmil multi-conformer modelling

This notebook introduces the high-level API for building multi-conformer models with **QSARmil**. The API is designed to simplify benchmarking QSARmil against alternative approaches without requiring detailed knowledge of the underlying modelling configuration. As a result, the workflow remains concise and easy to follow. You can adapt the code below to your own dataset and run the complete **QSARmil** modelling pipeline with minimal modifications.

In [1]:
import pandas as pd

from sklearn.metrics import r2_score

### 1. Data load

As an example, we use a publicly available and easily accessible collection of molecular bioactivity datasets introduced in the paper by:

> Van Tilborg, Derek, Alisa Alenicheva, and Francesca Grisoni. "Exposing the limitations of molecular machine learning with activity cliffs." Journal of chemical information and modeling 62.23 (2022): 5938-5951.

From this collection, we select one dataset for demonstration purposes.

In [2]:
# load data
url = "https://raw.githubusercontent.com/molML/MoleculeACE/main/MoleculeACE/Data/benchmark_data/CHEMBL2034_Ki.csv"
df_ace = pd.read_csv(url)

# train/test split
df_train = df_ace[df_ace["split"] == "train"][["smiles", "y"]]
df_test = df_ace[df_ace["split"] == "test"][["smiles", "y"]]

In [3]:
# uncomment for quick testing
df_train = df_train.sample(frac=0.1, random_state=42).reset_index(drop=True)
df_test = df_test.sample(frac=0.1, random_state=42).reset_index(drop=True)
df_train.shape, df_test.shape

((60, 2), (15, 2))

### 2. Data validation

The data validation step is straightforward but includes an additional requirement compared to standard 2D modelling pipelines. In most QSAR workflows, input structures are primarily validated by checking whether their SMILES strings are valid and can be successfully parsed into molecular objects.

In contrast, **QSARmil** introduces an extra validation step: verifying whether a valid 3D structure can be generated for each molecule. Molecules that fail this step cannot be used in the 3D modelling pipeline. As a result, the filtering (removal) rate in QSARmil may be higher than in typical 2D QSAR workflows.

In [4]:
from qsarmil.data.input_data import DataValidator

In [5]:
dvalid = DataValidator(num_cpu=30, verbose=True)

df_train = dvalid.filter_dataframe(df_train)
df_test = dvalid.filter_dataframe(df_test)

No rows removed. All molecules are valid.
No rows removed. All molecules are valid.

### 3. Building model

The multi-conformer model building pipeline consists of several sequential steps:

 - Conformer generation: the maximum number of conformers is defined using the ``num_conf`` parameter.
 - Descriptor calculation: by default, multiple types of 3D molecular descriptors are computed.
 - Model training: several multi-instance learning networks are used to train models. Internal stepwise hyperparameter optimization can be enabled with ``hopt=True`` (note that this increases runtime).
 - Consensus search: once multiple multi-conformer models are trained, a genetic algorithm is applied to identify an optimal consensus model.

Task type is defined automatically (regression or binary classification), ``output_folder`` (directory for storing predictions from individual models), and ``verbose`` (controls the level of pipeline progress output).

In [6]:
from qsarmil.meta import MultiConformerModel

In [7]:
model = MultiConformerModel(num_conf=10, hopt=False, verbose=True, output_folder="./mcfm")
df_pred = model.run_predict(df_train, df_test)

No rows removed. All molecules are valid.
No rows removed. All molecules are valid.
No rows removed. All molecules are valid.
Generating conformers: 48/48
Generating conformers: 12/12
Generating conformers: 12/12
[1/72] Running model: RDKitGEOM|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.156 GB
[2/72] Running model: RDKitGEOM|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.157 GB
[3/72] Running model: RDKitGEOM|MeanBagNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.160 GB
[4/72] Running model: RDKitGEOM|MeanInstanceNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.162 GB
[5/72] Running model: RDKitGEOM|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.163 GB
[6/72] Running model: RDKitGEOM|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.165 GB
[7/72] Running model: RDKitGEOM|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.165 GB
[8/72] Running model: RDKitGEOM|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.167 GB
[9/72] Running model: RDKitAUTOCORR|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.06 min | Memory usage: 1.226 GB
[10/72] Running model: RDKitAUTOCORR|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.227 GB
[11/72] Running model: RDKitAUTOCORR|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.231 GB
[12/72] Running model: RDKitAUTOCORR|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.231 GB
[13/72] Running model: RDKitAUTOCORR|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.233 GB
[14/72] Running model: RDKitAUTOCORR|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.234 GB
[15/72] Running model: RDKitAUTOCORR|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.236 GB
[16/72] Running model: RDKitAUTOCORR|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.237 GB
[17/72] Running model: RDKitRDF|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.04 min | Memory usage: 1.243 GB
[18/72] Running model: RDKitRDF|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.244 GB
[19/72] Running model: RDKitRDF|MeanBagNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.247 GB
[20/72] Running model: RDKitRDF|MeanInstanceNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.250 GB
[21/72] Running model: RDKitRDF|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.251 GB
[22/72] Running model: RDKitRDF|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.254 GB
[23/72] Running model: RDKitRDF|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.256 GB
[24/72] Running model: RDKitRDF|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.258 GB
[25/72] Running model: RDKitMORSE|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.07 min | Memory usage: 1.260 GB
[26/72] Running model: RDKitMORSE|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.260 GB
[27/72] Running model: RDKitMORSE|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.260 GB
[28/72] Running model: RDKitMORSE|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.261 GB
[29/72] Running model: RDKitMORSE|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.262 GB
[30/72] Running model: RDKitMORSE|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.263 GB
[31/72] Running model: RDKitMORSE|HopfieldAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.264 GB
[32/72] Running model: RDKitMORSE|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.266 GB
[33/72] Running model: RDKitWHIM|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.04 min | Memory usage: 1.267 GB
[34/72] Running model: RDKitWHIM|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.267 GB
[35/72] Running model: RDKitWHIM|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.268 GB
[36/72] Running model: RDKitWHIM|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.268 GB
[37/72] Running model: RDKitWHIM|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.270 GB
[38/72] Running model: RDKitWHIM|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.271 GB
[39/72] Running model: RDKitWHIM|HopfieldAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.272 GB
[40/72] Running model: RDKitWHIM|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.272 GB
[41/72] Running model: MolFeatUSRD|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.04 min | Memory usage: 1.293 GB
[42/72] Running model: MolFeatUSRD|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.294 GB
[43/72] Running model: MolFeatUSRD|MeanBagNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.297 GB
[44/72] Running model: MolFeatUSRD|MeanInstanceNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.297 GB
[45/72] Running model: MolFeatUSRD|AdditiveAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.299 GB
[46/72] Running model: MolFeatUSRD|SelfAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.300 GB
[47/72] Running model: MolFeatUSRD|HopfieldAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.301 GB
[48/72] Running model: MolFeatUSRD|DynamicPoolingNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.301 GB
[49/72] Running model: MolFeatElectroShape|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.06 min | Memory usage: 1.315 GB
[50/72] Running model: MolFeatElectroShape|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.316 GB
[51/72] Running model: MolFeatElectroShape|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.319 GB
[52/72] Running model: MolFeatElectroShape|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.320 GB
[53/72] Running model: MolFeatElectroShape|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.321 GB
[54/72] Running model: MolFeatElectroShape|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.321 GB
[55/72] Running model: MolFeatElectroShape|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.322 GB
[56/72] Running model: MolFeatElectroShape|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.323 GB
[57/72] Running model: RDKitGETAWAY|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.05 min | Memory usage: 1.353 GB
[58/72] Running model: RDKitGETAWAY|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.354 GB
[59/72] Running model: RDKitGETAWAY|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.360 GB
[60/72] Running model: RDKitGETAWAY|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.361 GB
[61/72] Running model: RDKitGETAWAY|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.363 GB
[62/72] Running model: RDKitGETAWAY|SelfAttentionNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.367 GB
[63/72] Running model: RDKitGETAWAY|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.368 GB
[64/72] Running model: RDKitGETAWAY|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.370 GB
[65/72] Running model: MolFeatPmapper|MeanInstanceWrapperMLPNetworkRegressor
  > Finished in 0.02 min | Memory usage: 1.426 GB
[66/72] Running model: MolFeatPmapper|MeanBagWrapperMLPNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.429 GB
[67/72] Running model: MolFeatPmapper|MeanBagNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.443 GB
[68/72] Running model: MolFeatPmapper|MeanInstanceNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.457 GB
[69/72] Running model: MolFeatPmapper|AdditiveAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.469 GB
[70/72] Running model: MolFeatPmapper|SelfAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.487 GB
[71/72] Running model: MolFeatPmapper|HopfieldAttentionNetworkRegressor
  > Finished in 0.01 min | Memory usage: 1.500 GB
[72/72] Running model: MolFeatPmapper|DynamicPoolingNetworkRegressor
  > Finished in 0.00 min | Memory usage: 1.508 GB

Running genetic consensus search ...
Note: this step's randomness isn't controlled by `seed` - qsarcons.GeneticSearch doesn't expose one.
Best consensus:
RDKitGETAWAY|HopfieldAttentionNetworkRegressor
RDKitMORSE|DynamicPoolingNetworkRegressor
No rows removed. All molecules are valid.
Generating conformers: 15/15

In [8]:
r2_score(df_test["y"], df_pred["pred"])

-0.14117049439768015

In [9]:
model.save()

In [10]:
preds = model.predict(df_test)
preds

No rows removed. All molecules are valid.
Using cached descriptor values for RDKitGEOM
Using cached descriptor values for RDKitAUTOCORR
Using cached descriptor values for RDKitRDF
Using cached descriptor values for RDKitMORSE
Using cached descriptor values for RDKitWHIM
Using cached descriptor values for MolFeatUSRD
Using cached descriptor values for MolFeatElectroShape
Using cached descriptor values for RDKitGETAWAY
Using cached descriptor values for MolFeatPmapper

                                               SMILES      pred
0   C[C@H]1c2c(cc(F)c(-c3cccc4c(Cl)c[nH]c34)c2F)NC... -0.476398
1   CNC(=O)C[C@H]1COc2cc(F)c(CC(C)C)cc2N1C(=O)c1cc... -2.145782
2   CNC(=O)c1cccc(CC[C@]2(O)CCC3=Cc4c(cnn4-c4ccc(F... -0.755328
3   CC(=O)[C@@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@... -3.595974
4   Cn1cc(S(=O)(=O)N2CC[C@H]3Cc4c(cnn4-c4ccc(F)cc4... -0.918757
5   C[C@]12C[C@H](O)[C@@]3(F)[C@@H](C[C@H](F)C4=CC... -0.163066
6   COc1c(O)ccc2c1-c1ccc3c(c1/C(=C/c1sccc1C(O)C(F)...  0.162163
7      C=C1C[C@H](C)CC(C)(C)[C@@H]1Cc1cc(OC)c(Br)cc1O -3.912323
8   CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccc(F)c(F)c1)... -0.897260
9      CC1=CC(C)(C)Nc2ccc3c(c21)C(CCC(C)C)Oc1ccccc1-3 -2.240073
10  O=C(c1ccccn1)[C@]12Cc3cnn(-c4ccc(F)cc4)c3C[C@@... -1.538211
11  Cc1ccnc(C(=O)[C@]23Cc4cnn(-c5ccc(F)cc5)c4C=C2C... -0.017571
12  CC(C)(C(=O)Nc1nccs1)C(c1ccc2c(cnn2-c2ccc(F)cc2... -0.458721
13    CC1=CC(C)(C)Nc2ccc3c(c21)C(c1ccccc1)Oc1ccccc1-3 -1.721643
14  C[C@H]1c2c(cc(F)c(-c3cccc4cc[nH]c34)c2F)NC(C)(... -1.097418

In [11]:
r2_score(df_test["y"], preds["pred"])

-0.14117049439768015

In [12]:
model = MultiConformerModel.load("./mcfm/model.pkl")
model.predictFromSMILES(df_test["smiles"])

No rows removed. All molecules are valid.
Generating conformers: 15/15
Rebuilding trainer for InstanceWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for InstanceNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for AdditiveAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (attention): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for SelfAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (q_proj): Linear(in_features=64, out_features=64, bias=True)
  (k_proj): Linear(in_features=64, out_features=64, bias=True)
  (v_proj): Linear(in_features=64, out_features=64, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for HopfieldAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for DynamicPoolingNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=11, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Norm()
  (dynamic_pooling): DynamicPooling()
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for InstanceWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for InstanceNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for AdditiveAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (attention): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for SelfAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (q_proj): Linear(in_features=64, out_features=64, bias=True)
  (k_proj): Linear(in_features=64, out_features=64, bias=True)
  (v_proj): Linear(in_features=64, out_features=64, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for HopfieldAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for DynamicPoolingNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=80, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Norm()
  (dynamic_pooling): DynamicPooling()
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for InstanceWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagWrapperMLPNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for BagNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for InstanceNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"pool":               mean
"random_seed":        42
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for AdditiveAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (attention): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for SelfAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
  (q_proj): Linear(in_features=64, out_features=64, bias=True)
  (k_proj): Linear(in_features=64, out_features=64, bias=True)
  (v_proj): Linear(in_features=64, out_features=64, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False
"weight_decay":       0.0
Rebuilding trainer for HopfieldAttentionNetworkRegressor(
  (instance_transformer): Sequential(
    (0): Linear(in_features=210, out_features=256, bias=True)
    (1): GELU(approximate='none')
    (2): Linear(in_features=256, out_features=128, bias=True)
    (3): GELU(approximate='none')
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): GELU(approximate='none')
  )
  (bag_estimator): Linear(in_features=64, out_features=1, bias=True)
) with parameters:
"accelerator":        cpu
"activation":         gelu
"batch_size":         128
"early_stopping":     True
"hidden_layer_sizes": (256, 128, 64)
"instance_dropout":   0.0
"learning_rate":      0.001
"max_epochs":         1000
"num_workers":        0
"random_seed":        42
"tau":                1.0
"verbose":            False

                                               SMILES      pred
0   C[C@H]1c2c(cc(F)c(-c3cccc4c(Cl)c[nH]c34)c2F)NC... -0.476398
1   CNC(=O)C[C@H]1COc2cc(F)c(CC(C)C)cc2N1C(=O)c1cc... -2.145782
2   CNC(=O)c1cccc(CC[C@]2(O)CCC3=Cc4c(cnn4-c4ccc(F... -0.755328
3   CC(=O)[C@@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@... -3.595974
4   Cn1cc(S(=O)(=O)N2CC[C@H]3Cc4c(cnn4-c4ccc(F)cc4... -0.918757
5   C[C@]12C[C@H](O)[C@@]3(F)[C@@H](C[C@H](F)C4=CC... -0.163066
6   COc1c(O)ccc2c1-c1ccc3c(c1/C(=C/c1sccc1C(O)C(F)...  0.162163
7      C=C1C[C@H](C)CC(C)(C)[C@@H]1Cc1cc(OC)c(Br)cc1O -3.912323
8   CC1=CC(C)(C)Nc2ccc3c(c21)/C(=C/c1ccc(F)c(F)c1)... -0.897260
9      CC1=CC(C)(C)Nc2ccc3c(c21)C(CCC(C)C)Oc1ccccc1-3 -2.240073
10  O=C(c1ccccn1)[C@]12Cc3cnn(-c4ccc(F)cc4)c3C[C@@... -1.538211
11  Cc1ccnc(C(=O)[C@]23Cc4cnn(-c5ccc(F)cc5)c4C=C2C... -0.017571
12  CC(C)(C(=O)Nc1nccs1)C(c1ccc2c(cnn2-c2ccc(F)cc2... -0.458721
13    CC1=CC(C)(C)Nc2ccc3c(c21)C(c1ccccc1)Oc1ccccc1-3 -1.721643
14  C[C@H]1c2c(cc(F)c(-c3cccc4cc[nH]c34)c2F)NC(C)(... -1.097418

In [13]:
# works on unknown SMILES as well, no caching in that case
model.predictFromSMILES(
    [
        "CN1[C@H]2CC[C@@H]1[C@@H](C(OC)=O)[C@@H](OC(C3=CC=CC=C3)=O)C2",
        "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"
    ]
)

No rows removed. All molecules are valid.
Generating conformers: 2/2

                                              SMILES      pred
0  CN1[C@H]2CC[C@@H]1[C@@H](C(OC)=O)[C@@H](OC(C3=... -3.468972
1                      CC(C)CC1=CC=C(C=C1)C(C)C(=O)O -3.105506

In [14]:
# second call uses cached descriptors for the same SMILES, so it is faster
model.predictFromSMILES(
    [
        "CN1[C@H]2CC[C@@H]1[C@@H](C(OC)=O)[C@@H](OC(C3=CC=CC=C3)=O)C2",
        "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O"
    ]
)

No rows removed. All molecules are valid.
Using cached descriptor values for RDKitGEOM
Using cached descriptor values for RDKitAUTOCORR
Using cached descriptor values for RDKitRDF
Using cached descriptor values for RDKitMORSE
Using cached descriptor values for RDKitWHIM
Using cached descriptor values for MolFeatUSRD
Using cached descriptor values for MolFeatElectroShape
Using cached descriptor values for RDKitGETAWAY
Using cached descriptor values for MolFeatPmapper

                                              SMILES      pred
0  CN1[C@H]2CC[C@@H]1[C@@H](C(OC)=O)[C@@H](OC(C3=... -3.468972
1                      CC(C)CC1=CC=C(C=C1)C(C)C(=O)O -3.105506